name: API.NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: api

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Get LFTP
      run: sudo apt install lftp
    - name: Configure LFTP
      run: mkdir ~/.lftp && echo "set ssl:verify-certificate false;" >> ~/.lftp/rc
    - name: Load Secrets
      run: echo "machine ${{ secrets.API_FTP_HOSTNAME }} login ${{ secrets.API_FTP_USERNAME }} password ${{ secrets.API_FTP_PASSWORD }}" > ~/.netrc
    - name: Upload Folder
      run: lftp -e "mirror --parallel=100 -R ./ /${{ secrets.API_FTP_PATH }}/" ${{ secrets.API_FTP_HOSTNAME }}
