name: API.NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
defaults:
  run:
    working-directory: api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  publish:
    needs: [ build ]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
        
    steps:
    - name: Publish
      run: dotnet publish -c Release --output ./release
    - name: Add secrets
      run: printf '${{ secrets.API_SECRET_FILE }}' > ./release/secrets.json
    - name: Install LFTP
      run: sudo apt install lftp
    - name: Configure LFTP
      run: mkdir ~/.lftp && echo "set ssl:verify-certificate false;" >> ~/.lftp/rc
    - name: Deploy FTP
      working-directory: api/release
      run: lftp -e "mirror --parallel=100 -R ./ /${{ secrets.API_FTP_PATH }}/" -u ${{ secrets.API_FTP_USERNAME }},${{ secrets.API_FTP_PASSWORD }} ${{ secrets.API_FTP_HOSTNAME }}
