name: API CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/api.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/api.yml'
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        required: true
        default: false
        description: Publish
  
defaults:
  run:
    working-directory: api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  publish:
    needs: [ build ]
    if: github.event_name == 'push' || github.event.inputs.publish == 'true'
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Publish
      run: dotnet publish -c Release --output ./release
    - name: Add secrets
      run: printf '${{ secrets.API_SECRET_FILE }}' > ./release/secrets.json
    - name: Install LFTP
      run: sudo apt install lftp
    - name: FTP Deploy
      working-directory: api/release
      run: lftp -e "mirror --parallel=100 -R ./ /${{ secrets.API_FTP_PATH }}/" -u ${{ secrets.API_FTP_USERNAME }},${{ secrets.API_FTP_PASSWORD }} ${{ secrets.API_FTP_HOSTNAME }}
