name: Web CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        required: true
        default: false
        description: Publish
  
defaults:
  run:
    working-directory: web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: ./web/package-lock.json
    - name: Restore dependencies
      run: npm ci
    - name: Test
      run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    - name: Add production config
      run: cp ./src/assets/config.prod.json ./src/assets/config.json
    - name: Build
      run: npm run build
    - name: Add 404 page
      run: cp ./dist/saba/index.html ./dist/saba/404.html
    - name: Publish
      if: github.event_name == 'push' || github.event.inputs.publish == 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web/dist/saba
        cname: www.saba-lms.tk
        
