name: Web CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
defaults:
  run:
    working-directory: web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: ./web/package-lock.json
    - name: Restore dependencies
      run: npm ci
    - name: Test
      run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    - name: Add secrets
      run: printf '${{ secrets.WEB_SECRET_FILE }}' > ./src/assets/config.json
    - name: Build
      run: npm run build
    - name: Publish
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/saba
        
